### ISSUE TITLE
Parse error in cabal file

### ISSUE THREAD

**Issue by HugoPeters1024** [phadej/zinza#10]
I am having trouble installing this package, I have tried the following

`cabal update && cabal install zinza`
package not found

Download the tar.gz from hackage
`cabal install zinza-0.2.tar.gz`
cabal: Could not parse the cabal file zinza-0.2/zinza.cabal in
zinza-0.2.tar.gz

`git clone + cabal install zinza/`
cabal: zinza.cabal:31: Parse of field 'build-depends' failed.

Now I am not completely new to yaml so I took a look but actually all seems fine to me. Any ideas what's going on?

I am using Ubuntu 18.04 btw with cabal 1.24

**Comment by phadej** [comment]
`zinza` requires cabal-install-2.2 at minimum, though it's recommend to use the latest. As you or ubuntu, I'd recommend https://launchpad.net/~hvr/+archive/ubuntu/ghc
