### ISSUE TITLE
A polite notification that Hoogle returns null on "zinza" request

### ISSUE THREAD

**Issue by Anton-Latukha** [phadej/zinza#17]
Noticed that:

https://hoogle.haskell.org/?hoogle=zinza -- package name
<|> https://hoogle.haskell.org/?hoogle=Zinza  -- module name
<|> https://hoogle.haskell.org/?hoogle=%3A%3A+Zinza+a+%3D%3E+ModuleConfig+a+-%3E+FilePath+-%3E+String+-%3E+Either+CompileOrParseError+String -- type signature form package
-- always returns `null` for me currently:

![Screenshot-2021-11-11-19:03:21](https://user-images.githubusercontent.com/20933385/141338875-16306e73-06cd-4c97-aad6-62b1f0ea4f26.png)

& https://hackage.haskell.org/package/zinza is there on Hackage now.

So the package is not discoverable. I discovered it by reading the Cabal source code.

You probably know better than me what that might be.

**Comment by phadej** [comment]
`zinza` is not on Hackage. if you want it there, you are welcome to add it.

**Comment by phadej** [comment]
Correction, not on *Stackage*

**Comment by Anton-Latukha** [comment]
Neither `hnix-store-remote` (which I maintain) or some `esotericbot` package - but I belive package names are searchable by name in `hoogle`:

![Screenshot-2021-11-11-19:29:00](https://user-images.githubusercontent.com/20933385/141342446-2edeb246-f047-45c5-805b-5d35d1e53773.png)

But of course you know better why that is the case.

Ok. Thank you.

**Comment by Anton-Latukha** [comment]
Yep, I'd probably should not posted links to module name or type signature - because they indeed not searchable.

But I so far not encountered that null return for package names that exist.
