### ISSUE TITLE
Quickstart guide

### ISSUE THREAD

**Issue by HugoPeters1024** [phadej/zinza#9]
Hey!

This looks like a great project. Is there any documentation available? especially a quickstart guide with a minimal example would be awesome.

**Comment by phadej** [comment]
The all documentation is on Hackage: https://hackage.haskell.org/package/zinza-0.2/docs/Zinza.html There's a small example.

**Comment by HugoPeters1024** [comment]
ah great! from this page https://hackage.haskell.org/package/zinza it doesn't become clear that the documentation is available. But that certainly looks helpful to starting playing around with it, thanks!

**Comment by phadej** [comment]
Looking at the main modules of the libraries is generally useful, there's where the docs might be.
